// Behavioural tests for the one piece of genuinely new logic: turning Claude
// Code's on-disk transcript into the projection events the canvas consumes.
// The fixtures mirror shapes observed on a real machine, including the awkward
// ones (metadata lines first, one API message split across several lines).

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, appendFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { TranscriptSource, detectForks, promptText } from '../server/transcript.js'

/** Minimal stand-in for WorkspaceStore that records what the projector emits. */
function stubStore() {
  return {
    calls: [],
    projected: [],
    async projectSession(session, replayFrom, title) { this.calls.push(['session', session.id, title]); this.projected.push(...session.events) },
    async projectEvents(session, events, title) { this.calls.push(['events', session.id, title]); this.projected.push(...events) },
  }
}

async function fixture(lines) {
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-'))
  const project = join(root, 'F--Project-Demo')
  await mkdir(project, { recursive: true })
  const file = join(project, 'aaaaaaaa-1111-2222-3333-444444444444.jsonl')
  await writeFile(file, lines.map(line => `${JSON.stringify(line)}\n`).join(''), 'utf8')
  return { root, file, cleanup: () => rm(root, { recursive: true, force: true }) }
}

const userLine = (text) => ({ type: 'user', uuid: 'u1', timestamp: '2026-01-01T00:00:00.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', message: { role: 'user', content: text } })
const assistantLine = (id, index, block) => ({ type: 'assistant', uuid: `a${index}`, timestamp: '2026-01-01T00:00:01.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', message: { id, role: 'assistant', content: [block] } })

test('metadata lines lead the file, so cwd must be found later', async () => {
  const { root, cleanup } = await fixture([
    { type: 'last-prompt', leafUuid: 'x', sessionId: 's1' },       // no cwd at all
    { type: 'mode', mode: 'normal', sessionId: 's1' },
    userLine('你好'),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    // The 43-of-63 trap: assuming line 0 carries cwd would drop this session.
    assert.equal(store.calls.length, 1, 'session projected exactly once')
    assert.deepEqual(store.calls[0], ['session', 'aaaaaaaa-1111-2222-3333-444444444444', 'T'])
    const [event] = store.projected
    assert.equal(event.type, 'user/message')
    assert.equal(event.seq, 2, 'seq is the file line index, metadata included')
  } finally { await cleanup() }
})

test('injected scaffolding is not a user turn, but a slash command keeps its arguments', async () => {
  const { root, cleanup } = await fixture([
    userLine('<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>'),
    userLine('<local-command-stdout>Enabled plan mode</local-command-stdout>'),
    userLine('<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>'),
    // Up to 32 KB per line in the real corpus; must never become a card.
    userLine('<task-notification><task-id>abc</task-id><status>completed</status><result>huge</result></task-notification>'),
    userLine({ type: 'text', text: 'array content is a tool result, not a prompt' }),
    // A compaction summary is a user line but machine-authored recap text; the
    // turns it recaps are still on disk and already projected.
    { type: 'user', uuid: 'c1', timestamp: '2026-01-01T00:00:00.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: 'This session is being continued from a previous conversation…', isCompactSummary: true } },
    userLine('<command-name>/graphify</command-name>\n<command-message>graphify</command-message>\n<command-args>F:\\Project\\X --mode deep</command-args>'),
    userLine('真正的提问'),
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    const prompts = store.projected.filter(event => event.type === 'user/message').map(event => event.data.content[0].text)
    // `/model` with no args is housekeeping; `/graphify <path>` is the intent.
    assert.deepEqual(prompts, ['/graphify F:\\Project\\X --mode deep', '真正的提问'])
  } finally { await cleanup() }
})

test('promptText classifies the shapes seen on disk', () => {
  assert.equal(promptText('你好'), '你好')
  assert.equal(promptText('  '), null)
  assert.equal(promptText('<local-command-stdout>x</local-command-stdout>'), null)
  assert.equal(promptText('<system-reminder>note</system-reminder>'), null)
  assert.equal(promptText('<command-name>/clear</command-name><command-args></command-args>'), null)
  assert.equal(promptText('<command-name>/plan</command-name><command-args>做一件事</command-args>'), '/plan 做一件事')
})

test('one API message split across lines collapses to one assistant card', async () => {
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_a', 0, { type: 'thinking', thinking: 'hmm' }),
    assistantLine('msg_a', 1, { type: 'text', text: '第一段' }),
    assistantLine('msg_a', 2, { type: 'tool_use', id: 'toolu_1', name: 'Read', input: { file_path: 'x' } }),
    assistantLine('msg_a', 3, { type: 'tool_use', id: 'toolu_2', name: 'Bash', input: { command: 'ls' } }),
    { type: 'user', uuid: 'r1', timestamp: '2026-01-01T00:00:02.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'file body' }] }, toolUseResult: { type: 'text' } },
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    const assistants = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(assistants.length, 1, 'text blocks of one message.id are one card')
    assert.equal(assistants[0].data.message.content[0].text, '第一段')
    assert.equal(assistants[0].data.turn, 1, 'stamped with the turn it answers')

    const calls = store.projected.filter(event => event.type === 'tool/call')
    assert.deepEqual(calls.map(call => call.data.callId), ['toolu_1', 'toolu_2'])
    assert.deepEqual(calls.map(call => call.data.turn), [1, 1], 'turn/step let the store fold tools into this turn')

    const [result] = store.projected.filter(event => event.type === 'tool/result')
    assert.equal(result.data.message.source.callId, 'toolu_1', 'paired to its call by callId')
    assert.equal(result.data.message.content[0].text, 'file body')
    // Without a matching turn/step the store cannot find the card to fold the
    // result into, and every tool ends up with result: null on the canvas.
    assert.equal(result.data.turn, 1)
    assert.equal(result.data.step, 1)
    assert.deepEqual(
      [calls[0].data.turn, calls[0].data.step],
      [result.data.turn, result.data.step],
      'a result is stamped exactly like the call it answers',
    )

    // End-to-end through the store: the call and its result become one record.
    const store2 = (await import('../server/workspace-store.js')).WorkspaceStore
    const directory = await mkdtemp(join(tmpdir(), 'ccsynapse-store-'))
    const workspaceStore = new store2(join(directory, 'state.json'))
    const session = { id: 'sess', title: 'T', header: { cwd: 'F:\\Project\\Demo' }, firstLiveSeq: 0, events: store.projected }
    const thread = await workspaceStore.projectSession(session, 0, 'T')
    const folded = thread.messages.flatMap(message => message.process ?? [])
    assert.equal(folded.length, 2)
    assert.deepEqual(folded.map(item => [item.callId, item.result]), [['toolu_1', 'file body'], ['toolu_2', null]])
    assert.equal(thread.pendingProcess.length, 0, 'nothing left stranded')
    await rm(directory, { recursive: true, force: true })
  } finally { await cleanup() }
})

test('appended lines project incrementally, keeping seq monotonic', async () => {
  const { root, file, cleanup } = await fixture([userLine('第一问')])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    assert.deepEqual(store.calls.map(call => call[0]), ['session'], 'first sighting replays whole')

    await appendFile(file, `${JSON.stringify(userLine('第二问'))}\n`, 'utf8')
    await source.sync(store, 'T')
    assert.deepEqual(store.calls.map(call => call[0]), ['session', 'events'], 'later polls feed only the tail')
    const appended = store.projected.filter(event => event.type === 'user/message' && event.data.content[0].text === '第二问')
    assert.equal(appended.length, 1)
  } finally { await cleanup() }
})

test('oversized tool payloads are capped so the state file stays bounded', async () => {
  const huge = 'x'.repeat(88_393)   // the largest single argument measured on disk
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_big', 0, { type: 'text', text: 'ok' }),
    assistantLine('msg_big', 1, { type: 'tool_use', id: 'toolu_big', name: 'Write', input: { content: huge } }),
    { type: 'user', uuid: 'r9', timestamp: '2026-01-01T00:00:03.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'toolu_big', content: huge }] }, toolUseResult: {} },
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    const call = store.projected.find(event => event.type === 'tool/call')
    const result = store.projected.find(event => event.type === 'tool/result')
    assert.ok(call.data.arguments.length < 2_100, `argument capped, got ${call.data.arguments.length}`)
    assert.ok(result.data.message.content[0].text.length < 2_100, 'result capped')
    assert.match(call.data.arguments, /已截断）$/)
  } finally { await cleanup() }
})

test('a trailing assistant message is held one poll, then released', async () => {
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_z', 0, { type: 'text', text: '还在写' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    // Held: the group touches EOF, so more text of the same message may follow.
    assert.equal(store.projected.filter(event => event.type === 'assistant/message').length, 0)

    await source.sync(store, 'T')   // file unchanged -> the turn is over
    const released = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(released.length, 1)
    assert.equal(released[0].data.message.content[0].text, '还在写')
  } finally { await cleanup() }
})

test('known metadata entry types are skipped quietly', async () => {
  const { root, cleanup } = await fixture([
    { type: 'agent-name', agentName: 'Explore', cwd: 'F:\\Project\\Demo', sessionId: 's1' },
    { type: 'pr-link', url: 'https://example.test/1', cwd: 'F:\\Project\\Demo', sessionId: 's1' },
    userLine('问题'),
  ])
  const warnings = []
  const realWarn = console.warn
  console.warn = (...args) => warnings.push(args.join(' '))
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    assert.equal(store.projected.filter(event => event.type === 'user/message').length, 1)
    // These are in Claude Code's own entry union, so they must not read as
    // "unknown type" the way a genuinely new entry kind would.
    assert.deepEqual(warnings.filter(line => line.includes('unknown entry type')), [])
  } finally { console.warn = realWarn; await cleanup() }
})

test('unknown entry types are skipped, never thrown on', async () => {
  const { root, cleanup } = await fixture([
    userLine('问题'),
    { type: 'some-future-entry-type', payload: { nested: true } },
    { type: 'assistant', message: { id: 'm', content: [{ type: 'brand-new-block', data: 'x' }] } },
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    assert.equal(store.projected.filter(event => event.type === 'user/message').length, 1)
  } finally { await cleanup() }
})

test('detectForks links a child whose leading prompts are a prefix of the parent', () => {
  const sessions = new Map([
    ['parent', { id: 'parent', fingerprint: ['a', 'b'], turnSeqs: [5, 20], lastSeq: 40 }],
    ['child', { id: 'child', fingerprint: ['a', 'b', 'c'], turnSeqs: [5, 20, 31], lastSeq: 50 }],
    ['unrelated', { id: 'unrelated', fingerprint: ['z'], turnSeqs: [3], lastSeq: 9 }],
  ])
  const forks = detectForks(sessions)
  assert.deepEqual([...forks.keys()], ['child'])
  // seedLength is in the PARENT's seq space: the boundary sits at the parent's
  // next turn, so exactly the two shared turns stay inside the fork cut.
  assert.deepEqual(forks.get('child'), { parentSessionId: 'parent', seedLength: 40 })
})

test('a fork is linked but a re-asked question is not, end to end', async () => {
  // A `--fork-session` copy preserves replies verbatim; re-sending the same
  // prompt in a fresh session produces a different answer. Both look identical
  // if you fingerprint only the questions, which is what made two ordinary
  // retries show up as branches on a real corpus.
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-fork-'))
  const project = join(root, 'F--Project-Demo')
  await mkdir(project, { recursive: true })
  const write = async (id, lines, extra = []) => writeFile(join(project, `${id}.jsonl`), [...lines, ...extra].map(line => `${JSON.stringify(line)}\n`).join(''), 'utf8')

  const turn = (prompt, answer) => [
    userLine(prompt),
    assistantLine(prompt, 0, { type: 'text', text: answer }),
    // A new prompt closes the previous turn, so give each turn a successor.
  ]
  const close = () => [userLine('下一问'), assistantLine('下一问', 0, { type: 'text', text: '下一答' })]

  const t1 = turn('q1', 'a1')
  const t2 = turn('q2', 'a2')
  await write('parent000-0000-0000-0000-000000000000', [...t1, ...t2, ...close()])
  // Fork: identical history, one extra turn appended.
  await write('child0000-0000-0000-0000-000000000000', [...t1, ...t2, ...close(), userLine('分支的新问题')])
  // Retry: same questions, different answers.
  await write('retry0000-0000-0000-0000-000000000000', [
    userLine('q1'), assistantLine('q1', 0, { type: 'text', text: 'DIFFERENT' }),
    userLine('q2'), assistantLine('q2', 0, { type: 'text', text: 'ALSO DIFFERENT' }),
    ...close(),
  ])

  try {
    const source = new TranscriptSource(root)
    await source.sync(stubStore(), 'T')
    const forks = detectForks(source.sessions)
    assert.deepEqual([...forks.keys()], ['child0000-0000-0000-0000-000000000000'],
      'only the verbatim copy is a fork; the retry is not')
    assert.equal(forks.get('child0000-0000-0000-0000-000000000000').parentSessionId, 'parent000-0000-0000-0000-000000000000')
  } finally { await rm(root, { recursive: true, force: true }) }
})

test('detectForks prefers the longest matching parent and ignores non-prefixes', () => {
  const sessions = new Map([
    ['root', { id: 'root', fingerprint: ['a', 'b'], turnSeqs: [1, 8], lastSeq: 25 }],
    ['mid', { id: 'mid', fingerprint: ['a', 'b', 'c'], turnSeqs: [1, 8, 19], lastSeq: 40 }],
    ['leaf', { id: 'leaf', fingerprint: ['a', 'b', 'c', 'd'], turnSeqs: [1, 8, 19, 30], lastSeq: 50 }],
    ['other', { id: 'other', fingerprint: ['a', 'x', 'y'], turnSeqs: [1, 4, 9], lastSeq: 12 }],
  ])
  const forks = detectForks(sessions)
  assert.equal(forks.get('leaf').parentSessionId, 'mid', 'longest shared prefix wins, not root')
  assert.equal(forks.get('mid').parentSessionId, 'root')
  assert.equal(forks.has('other'), false, 'a diverging second prompt is not a fork')
})

test('detectForks needs more than one shared turn, so a common opener is not a fork', () => {
  // "你好" opens many unrelated sessions; one shared turn must not link them.
  const sessions = new Map([
    ['first', { id: 'first', fingerprint: ['hi', 'a'], turnSeqs: [1, 8], lastSeq: 20 }],
    ['second', { id: 'second', fingerprint: ['hi', 'b'], turnSeqs: [1, 8], lastSeq: 20 }],
  ])
  assert.equal(detectForks(sessions).size, 0)
  assert.equal(detectForks(sessions, 1).size, 0, 'neither is a strict prefix of the other')
})

test('detectForks uses UUID intersection when available, never misidentifies a retry', async () => {
  // Fork: the child is a stale snapshot, so it holds a SUBSET of the parent's
  // UUIDs — the original is the one that kept appending.
  const parentUuids = new Set(['u1', 'u2', 'u3', 'u4', 'u5'])
  const childUuids  = new Set(['u1', 'u2', 'u3'])               // subset
  const retryUuids  = new Set(['r1', 'r2', 'r3'])               // disjoint

  const sessions = new Map([
    ['parent', { id: 'parent', uuidSet: parentUuids, fingerprint: [], turnSeqs: [], lastSeq: 50 }],
    ['child',  { id: 'child',  uuidSet: childUuids,  fingerprint: [], turnSeqs: [], lastSeq: 30 }],
    ['retry',  { id: 'retry',  uuidSet: retryUuids,  fingerprint: [], turnSeqs: [], lastSeq: 30 }],
  ])
  const forks = detectForks(sessions)
  assert.deepEqual([...forks.keys()], ['child'], 'only the UUID-subset is a fork')
  assert.equal(forks.get('child').parentSessionId, 'parent')
  assert.equal(forks.has('retry'), false, 'disjoint UUIDs are never a fork')
  assert.equal(forks.has('parent'), false, 'the original is never a child')
})

test('detectForks assigns the larger session as parent, so snapshots are siblings', () => {
  // A fork is a snapshot of the original: the original keeps growing, so it
  // holds MORE uuids. Three snapshots taken at different times all descend
  // from that one original — they must be siblings, not a chain.
  const core = ['u1', 'u2', 'u3', 'u4', 'u5']
  const sessions = new Map([
    ['origin', { id: 'origin', uuidSet: new Set([...core, 'o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'o8']), fingerprint: [], turnSeqs: [], lastSeq: 100 }],
    ['snapA',  { id: 'snapA',  uuidSet: new Set(core), fingerprint: [], turnSeqs: [], lastSeq: 30 }],
    ['snapB',  { id: 'snapB',  uuidSet: new Set([...core, 'o1', 'o2']), fingerprint: [], turnSeqs: [], lastSeq: 50 }],
  ])
  const forks = detectForks(sessions)
  assert.equal(forks.get('snapA')?.parentSessionId, 'origin')
  assert.equal(forks.get('snapB')?.parentSessionId, 'origin')
  assert.equal(forks.has('origin'), false, 'the original is never a child')
})
