// Behavioural tests for the one piece of genuinely new logic: turning Claude
// Code's on-disk transcript into the projection events the canvas consumes.
// The fixtures mirror shapes observed on a real machine, including the awkward
// ones (metadata lines first, one API message split across several lines).

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, appendFile, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import vm from 'node:vm'

import { TranscriptSource, detectForks, promptText } from '../server/transcript.js'

/** Minimal stand-in for WorkspaceStore that records what the projector emits. */
function stubStore() {
  return {
    calls: [],
    projected: [],
    async projectSession(session, replayFrom, title) { this.calls.push(['session', session.id, title]); this.projected.push(...session.events) },
    async projectEvents(session, events, title) { this.calls.push(['events', session.id, title]); this.projected.push(...events) },
  }
}

async function fixture(lines) {
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-'))
  const project = join(root, 'F--Project-Demo')
  await mkdir(project, { recursive: true })
  const file = join(project, 'aaaaaaaa-1111-2222-3333-444444444444.jsonl')
  await writeFile(file, lines.map(line => `${JSON.stringify(line)}\n`).join(''), 'utf8')
  return { root, file, cleanup: () => rm(root, { recursive: true, force: true }) }
}

const userLine = (text) => ({ type: 'user', uuid: 'u1', timestamp: '2026-01-01T00:00:00.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', message: { role: 'user', content: text } })
const assistantLine = (id, index, block) => ({ type: 'assistant', uuid: `a${index}`, timestamp: '2026-01-01T00:00:01.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', message: { id, role: 'assistant', content: [block] } })
const toolResultLine = (toolUseId, text) => ({ type: 'user', uuid: `r${toolUseId}`, timestamp: '2026-01-01T00:00:02.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: toolUseId, content: text }] }, toolUseResult: {} })
// Claude Code moves the payload of a large tool result into attachment lines
// that sit in the middle of the response's own write sequence.
const attachmentLine = (index) => ({ type: 'attachment', uuid: `att${index}`, timestamp: '2026-01-01T00:00:02.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', attachment: { type: 'tool-result-payload', content: 'x'.repeat(4096) } })

test('metadata lines lead the file, so cwd must be found later', async () => {
  const { root, cleanup } = await fixture([
    { type: 'last-prompt', leafUuid: 'x', sessionId: 's1' },       // no cwd at all
    { type: 'mode', mode: 'normal', sessionId: 's1' },
    userLine('你好'),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    // The 43-of-63 trap: assuming line 0 carries cwd would drop this session.
    assert.equal(store.calls.length, 1, 'session projected exactly once')
    assert.deepEqual(store.calls[0], ['session', 'aaaaaaaa-1111-2222-3333-444444444444', 'T'])
    const [event] = store.projected
    assert.equal(event.type, 'user/message')
    assert.equal(event.seq, 2, 'seq is the file line index, metadata included')
  } finally { await cleanup() }
})

test('injected scaffolding is not a user turn, but a slash command keeps its arguments', async () => {
  const { root, cleanup } = await fixture([
    userLine('<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>'),
    userLine('<local-command-stdout>Enabled plan mode</local-command-stdout>'),
    userLine('<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>'),
    // Up to 32 KB per line in the real corpus; must never become a card.
    userLine('<task-notification><task-id>abc</task-id><status>completed</status><result>huge</result></task-notification>'),
    userLine({ type: 'text', text: 'array content is a tool result, not a prompt' }),
    // A compaction summary is a user line but machine-authored recap text; the
    // turns it recaps are still on disk and already projected.
    { type: 'user', uuid: 'c1', timestamp: '2026-01-01T00:00:00.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: 'This session is being continued from a previous conversation…', isCompactSummary: true } },
    userLine('<command-name>/graphify</command-name>\n<command-message>graphify</command-message>\n<command-args>F:\\Project\\X --mode deep</command-args>'),
    userLine('真正的提问'),
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    const prompts = store.projected.filter(event => event.type === 'user/message').map(event => event.data.content[0].text)
    // `/model` with no args is housekeeping; `/graphify <path>` is the intent.
    assert.deepEqual(prompts, ['/graphify F:\\Project\\X --mode deep', '真正的提问'])
  } finally { await cleanup() }
})

test('promptText classifies the shapes seen on disk', () => {
  assert.equal(promptText('你好'), '你好')
  assert.equal(promptText('  '), null)
  assert.equal(promptText('<local-command-stdout>x</local-command-stdout>'), null)
  assert.equal(promptText('<system-reminder>note</system-reminder>'), null)
  assert.equal(promptText('<command-name>/clear</command-name><command-args></command-args>'), null)
  assert.equal(promptText('<command-name>/plan</command-name><command-args>做一件事</command-args>'), '/plan 做一件事')
})

test('one API message split across lines collapses to one assistant card', async () => {
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_a', 0, { type: 'thinking', thinking: 'hmm' }),
    assistantLine('msg_a', 1, { type: 'text', text: '第一段' }),
    assistantLine('msg_a', 2, { type: 'tool_use', id: 'toolu_1', name: 'Read', input: { file_path: 'x' } }),
    assistantLine('msg_a', 3, { type: 'tool_use', id: 'toolu_2', name: 'Bash', input: { command: 'ls' } }),
    { type: 'user', uuid: 'r1', timestamp: '2026-01-01T00:00:02.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'file body' }] }, toolUseResult: { type: 'text' } },
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    // The last line is this message's OWN tool result, which deliberately no
    // longer closes its group — the message could still continue after it. The
    // card is released once the file stops growing, exactly like any other
    // group sitting on EOF.
    await source.sync(store, 'T')
    const assistants = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(assistants.length, 1, 'text blocks of one message.id are one card')
    assert.equal(assistants[0].data.message.content[0].text, '第一段')
    assert.equal(assistants[0].data.turn, 1, 'stamped with the turn it answers')

    const calls = store.projected.filter(event => event.type === 'tool/call')
    assert.deepEqual(calls.map(call => call.data.callId), ['toolu_1', 'toolu_2'])
    assert.deepEqual(calls.map(call => call.data.turn), [1, 1], 'turn/step let the store fold tools into this turn')

    const [result] = store.projected.filter(event => event.type === 'tool/result')
    assert.equal(result.data.message.source.callId, 'toolu_1', 'paired to its call by callId')
    assert.equal(result.data.message.content[0].text, 'file body')
    // Without a matching turn/step the store cannot find the card to fold the
    // result into, and every tool ends up with result: null on the canvas.
    assert.equal(result.data.turn, 1)
    assert.equal(result.data.step, 1)
    assert.deepEqual(
      [calls[0].data.turn, calls[0].data.step],
      [result.data.turn, result.data.step],
      'a result is stamped exactly like the call it answers',
    )

    // End-to-end through the store: the call and its result become one record.
    const store2 = (await import('../server/workspace-store.js')).WorkspaceStore
    const directory = await mkdtemp(join(tmpdir(), 'ccsynapse-store-'))
    const workspaceStore = new store2(join(directory, 'state.json'))
    const session = { id: 'sess', title: 'T', header: { cwd: 'F:\\Project\\Demo' }, firstLiveSeq: 0, events: store.projected }
    const thread = await workspaceStore.projectSession(session, 0, 'T')
    const folded = thread.messages.flatMap(message => message.process ?? [])
    assert.equal(folded.length, 2)
    assert.deepEqual(folded.map(item => [item.callId, item.result]), [['toolu_1', 'file body'], ['toolu_2', null]])
    assert.equal(thread.pendingProcess.length, 0, 'nothing left stranded')
    await rm(directory, { recursive: true, force: true })
  } finally { await cleanup() }
})

test('a group stays open across the tool results of its own calls', async () => {
  // The risky shape: the model calls a tool, then keeps talking in the SAME API
  // message, and the transcript puts that call's result between the two halves.
  // Splitting there yields two assistant/message events for one message, and the
  // canvas — which chains a turn's assistant messages and renders only the last
  // — would silently drop the first half's text.
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_cut', 0, { type: 'text', text: '前段' }),
    assistantLine('msg_cut', 1, { type: 'tool_use', id: 'toolu_x', name: 'Skill', input: { skill: 'x' } }),
    toolResultLine('toolu_x', 'done'),
    assistantLine('msg_cut', 3, { type: 'text', text: '续写' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    await source.sync(store, 'T')   // trailing group is held one poll
    const assistants = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(assistants.length, 1, 'the result did not cut the message in two')
    assert.equal(assistants[0].data.message.content[0].text, '前段\n续写', 'both halves on one card')
    assert.match(assistants[0].data.message.content[0].text, /续写/)

    // The result must still be produced, stamped like the call it answers, or
    // every tool folds into nothing and shows result: null.
    const [result] = store.projected.filter(event => event.type === 'tool/result')
    assert.equal(result.data.message.source.callId, 'toolu_x')
    assert.equal(result.data.message.content[0].text, 'done')
    const [call] = store.projected.filter(event => event.type === 'tool/call')
    assert.equal(call.data.callId, 'toolu_x')
    assert.deepEqual([result.data.turn, result.data.step], [call.data.turn, call.data.step])

    // End-to-end through the store: the card comes first in the event stream
    // anyway, and the result that was emitted before it still lands on it.
    const { WorkspaceStore } = await import('../server/workspace-store.js')
    const directory = await mkdtemp(join(tmpdir(), 'ccsynapse-store-'))
    const workspaceStore = new WorkspaceStore(join(directory, 'state.json'))
    const session = { id: 'sess', title: 'T', header: { cwd: 'F:\\Project\\Demo' }, firstLiveSeq: 0, events: store.projected }
    const thread = await workspaceStore.projectSession(session, 0, 'T')
    assert.deepEqual(thread.messages.map(message => message.text), ['问题', '前段\n续写'])
    assert.deepEqual(thread.messages[1].process.map(item => [item.callId, item.result]), [['toolu_x', 'done']])
    assert.equal(thread.pendingProcess.length, 0, 'nothing left stranded')
    await rm(directory, { recursive: true, force: true })
  } finally { await cleanup() }
})

test('a tool result from another call still splits the group', async () => {
  // The control for the test above: the pass is granted by callId, not by the
  // line merely being a tool result. An id this group never issued keeps the old
  // behaviour, so the rule cannot quietly become "nothing closes a group".
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_cut', 0, { type: 'text', text: '前段' }),
    assistantLine('msg_cut', 1, { type: 'tool_use', id: 'toolu_x', name: 'Skill', input: { skill: 'x' } }),
    toolResultLine('toolu_other', 'done'),
    assistantLine('msg_cut', 3, { type: 'text', text: '续写' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    await source.sync(store, 'T')
    const texts = store.projected
      .filter(event => event.type === 'assistant/message')
      .map(event => event.data.message.content[0].text)
    assert.deepEqual(texts, ['前段', '续写'], 'a foreign result still ends the group')
  } finally { await cleanup() }
})

test('text split by an attachment line stays one card', async () => {
  // The shape measured on disk: the results of a message's own tool calls, then
  // the attachments holding their payloads, then another block of the SAME
  // message. Bridging only the results would leave this split — and the split is
  // safe only by luck of block order (text first, tool_use after), which is
  // exactly the luck this rule exists to stop depending on.
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_att', 0, { type: 'text', text: '前段' }),
    assistantLine('msg_att', 1, { type: 'tool_use', id: 'toolu_y', name: 'Skill', input: { skill: 'y' } }),
    toolResultLine('toolu_y', 'done'),
    attachmentLine(2),
    attachmentLine(3),
    assistantLine('msg_att', 4, { type: 'text', text: '续写' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    await source.sync(store, 'T')   // trailing group is held one poll
    const assistants = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(assistants.length, 1, 'the attachments did not cut the message in two')
    assert.equal(assistants[0].data.message.content[0].text, '前段\n续写', 'both halves on one card')
    // Attachments carry no event of their own, and bridging them must not eat
    // the call or its result either.
    assert.equal(store.projected.filter(event => event.type === 'tool/call').length, 1)
    assert.equal(store.projected.filter(event => event.type === 'tool/result').length, 1)
    assert.equal(store.projected.filter(event => event.type === 'tool/result')[0].data.message.content[0].text, 'done')
  } finally { await cleanup() }
})

test('a skill payload line does not split the group either', async () => {
  // Shape 3 measured on disk: the body of the skill that was just invoked arrives
  // as a `user` line carrying text blocks and no tool_result. It is not an answer
  // and not a prompt (a prompt is a plain string), and it emits no event of its
  // own — but it sits between two blocks of the SAME response, and closing on it
  // is what still cuts this message apart in the real session file.
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_skill', 0, { type: 'text', text: '前段' }),
    assistantLine('msg_skill', 1, { type: 'tool_use', id: 'toolu_s', name: 'Skill', input: { skill: 's' } }),
    toolResultLine('toolu_s', 'Launching skill: s'),
    { type: 'user', uuid: 'sk1', timestamp: '2026-01-01T00:00:02.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: [{ type: 'text', text: `Base directory for this skill: ${'x'.repeat(43_431)}` }] } },
    attachmentLine(2),
    assistantLine('msg_skill', 3, { type: 'text', text: '续写' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    await source.sync(store, 'T')   // trailing group is held one poll
    const assistants = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(assistants.length, 1, 'the payload did not cut the message in two')
    assert.equal(assistants[0].data.message.content[0].text, '前段\n续写')
    assert.equal(assistants[0].data.turn, 1, 'still the turn the model started answering')
    assert.equal(store.projected.some(event => event.type === 'user/message'), true, 'the opening prompt, and only it, is a user card')
  } finally { await cleanup() }
})

test('a real prompt or a system line still splits the group', async () => {
  // The other side of every widening above. Both are turn boundaries that must
  // never be merged across: a prompt starts a new question, and a `system` line
  // can be a compaction boundary whose pre-history the canvas cannot draw. If
  // either ever stops closing a group, this rule has been widened into "nothing
  // closes a group" and these fail.
  const cutters = [
    ['a prompt', userLine('第二个问题')],
    ['a system line', { type: 'system', subtype: 'compact_boundary', uuid: 'sy1', timestamp: '2026-01-01T00:00:02.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', content: 'boundary' }],
  ]
  for (const [what, cutter] of cutters) {
    const { root, cleanup } = await fixture([
      userLine('问题'),
      assistantLine('msg_sys', 0, { type: 'text', text: '前段' }),
      cutter,
      assistantLine('msg_sys', 3, { type: 'text', text: '续写' }),
    ])
    try {
      const store = stubStore()
      const source = new TranscriptSource(root)
      await source.sync(store, 'T')
      await source.sync(store, 'T')
      const texts = store.projected
        .filter(event => event.type === 'assistant/message')
        .map(event => event.data.message.content[0].text)
      assert.deepEqual(texts, ['前段', '续写'], `${what} must still end the group`)
    } finally { await cleanup() }
  }
})

test('appended lines project incrementally, keeping seq monotonic', async () => {
  const { root, file, cleanup } = await fixture([userLine('第一问')])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    assert.deepEqual(store.calls.map(call => call[0]), ['session'], 'first sighting replays whole')

    await appendFile(file, `${JSON.stringify(userLine('第二问'))}\n`, 'utf8')
    await source.sync(store, 'T')
    assert.deepEqual(store.calls.map(call => call[0]), ['session', 'events'], 'later polls feed only the tail')
    const appended = store.projected.filter(event => event.type === 'user/message' && event.data.content[0].text === '第二问')
    assert.equal(appended.length, 1)
  } finally { await cleanup() }
})

test('oversized tool payloads are capped so the state file stays bounded', async () => {
  const huge = 'x'.repeat(88_393)   // the largest single argument measured on disk
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_big', 0, { type: 'text', text: 'ok' }),
    assistantLine('msg_big', 1, { type: 'tool_use', id: 'toolu_big', name: 'Write', input: { content: huge } }),
    { type: 'user', uuid: 'r9', timestamp: '2026-01-01T00:00:03.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'toolu_big', content: huge }] }, toolUseResult: {} },
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    await source.sync(store, 'T')   // own result at EOF: released next poll
    const call = store.projected.find(event => event.type === 'tool/call')
    const result = store.projected.find(event => event.type === 'tool/result')
    assert.ok(call.data.arguments.length < 2_100, `argument capped, got ${call.data.arguments.length}`)
    assert.ok(result.data.message.content[0].text.length < 2_100, 'result capped')
    assert.match(call.data.arguments, /已截断）$/)
  } finally { await cleanup() }
})

test('a trailing assistant message is held one poll, then released', async () => {
  const { root, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_z', 0, { type: 'text', text: '还在写' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    // Held: the group touches EOF, so more text of the same message may follow.
    assert.equal(store.projected.filter(event => event.type === 'assistant/message').length, 0)

    await source.sync(store, 'T')   // file unchanged -> the turn is over
    const released = store.projected.filter(event => event.type === 'assistant/message')
    assert.equal(released.length, 1)
    assert.equal(released[0].data.message.content[0].text, '还在写')
  } finally { await cleanup() }
})

test('a held group exposes its partial text as live text, and release clears it', async () => {
  // The held group is the whole point: its text is NOT in the store yet, so
  // without this the canvas shows 「等待助手回复」 for the entire turn.
  const { root, file, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_live', 0, { type: 'text', text: '前半句' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    const sessions = await source.sync(store, 'T')
    assert.equal(store.projected.filter(event => event.type === 'assistant/message').length, 0, 'still held')
    assert.equal(sessions.get('aaaaaaaa-1111-2222-3333-444444444444').liveText, '前半句')

    // A real prompt closes the group. The text is a card from here on, and the
    // live copy must go away or the client keeps patching it over the answer.
    await appendFile(file, `${JSON.stringify(userLine('第二问'))}\n`, 'utf8')
    const after = await source.sync(store, 'T')
    assert.equal(after.get('aaaaaaaa-1111-2222-3333-444444444444').liveText, null)
  } finally { await cleanup() }
})

test('live text is capped like a projected message, and shows nothing without text', async () => {
  const { root, file, cleanup } = await fixture([
    userLine('问题'),
    assistantLine('msg_live', 0, { type: 'thinking', thinking: '先想一想' }),
  ])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    // Thinking alone is not text the user wrote or the model wrote down: an
    // empty string would make the client churn its placeholder once a second.
    assert.equal((await source.sync(store, 'T')).get('aaaaaaaa-1111-2222-3333-444444444444').liveText, null)

    await appendFile(file, `${JSON.stringify(assistantLine('msg_live', 1, { type: 'text', text: 'x'.repeat(9_000) }))}\n`, 'utf8')
    const capped = (await source.sync(store, 'T')).get('aaaaaaaa-1111-2222-3333-444444444444').liveText
    // Same cap and same marker the store would project, so the client can patch
    // this into the card the finished answer replaces without the two disagreeing.
    assert.ok(capped.length < 8_100, `capped, got ${capped.length}`)
    assert.match(capped, /详情查看全文）$/)
  } finally { await cleanup() }
})

test('known metadata entry types are skipped quietly', async () => {
  const { root, cleanup } = await fixture([
    { type: 'agent-name', agentName: 'Explore', cwd: 'F:\\Project\\Demo', sessionId: 's1' },
    { type: 'pr-link', url: 'https://example.test/1', cwd: 'F:\\Project\\Demo', sessionId: 's1' },
    userLine('问题'),
  ])
  const warnings = []
  const realWarn = console.warn
  console.warn = (...args) => warnings.push(args.join(' '))
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    assert.equal(store.projected.filter(event => event.type === 'user/message').length, 1)
    // These are in Claude Code's own entry union, so they must not read as
    // "unknown type" the way a genuinely new entry kind would.
    assert.deepEqual(warnings.filter(line => line.includes('unknown entry type')), [])
  } finally { console.warn = realWarn; await cleanup() }
})

test('unknown entry types are skipped, never thrown on', async () => {
  const { root, cleanup } = await fixture([
    userLine('问题'),
    { type: 'some-future-entry-type', payload: { nested: true } },
    { type: 'assistant', message: { id: 'm', content: [{ type: 'brand-new-block', data: 'x' }] } },
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    assert.equal(store.projected.filter(event => event.type === 'user/message').length, 1)
  } finally { await cleanup() }
})

test('a nested subagent hangs off the agent that spawned it, not the top session', async () => {
  // Real layout: every subagent of a session — nested ones included — is written
  // FLAT into one subagents/ directory, so the path only ever names the top-level
  // session. The meta file's toolUseId points at the Agent tool call that spawned
  // it, and the transcript that issued that call is the real parent.
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-nested-'))
  const main = 'aaaaaaaa-1111-2222-3333-444444444444'
  const project = join(root, 'F--Project-Demo')
  const subagents = join(project, main, 'subagents')
  await mkdir(subagents, { recursive: true })
  const write = (path, lines) => writeFile(path, Array.isArray(lines) ? lines.map(line => `${JSON.stringify(line)}\n`).join('') : lines, 'utf8')

  await write(join(project, `${main}.jsonl`), [userLine('主会话的提问')])
  await write(join(subagents, 'agent-aaa.jsonl'), [
    userLine('一级代理的提问'),
    // The spawn call: this is what makes agent-aaa the parent of agent-bbb.
    assistantLine('msg_a', 0, { type: 'tool_use', id: 'call_2', name: 'Agent', input: { prompt: 'go' } }),
  ])
  await write(join(subagents, 'agent-bbb.jsonl'), [userLine('二级代理的提问')])
  await write(join(subagents, 'agent-aaa.meta.json'), JSON.stringify({ toolUseId: 'call_1', spawnDepth: 1 }))
  await write(join(subagents, 'agent-bbb.meta.json'), JSON.stringify({ toolUseId: 'call_2', spawnDepth: 2 }))

  try {
    const source = new TranscriptSource(root)
    await source.sync(stubStore(), 'T')
    assert.equal(source.sessions.get('agent-bbb').parentSessionId, 'agent-aaa',
      'the spawner issues the tool call the child meta names')
    assert.equal(source.sessions.get('agent-aaa').parentSessionId, main,
      'a depth-1 agent still resolves to the session directory, which is right for it')
  } finally { await rm(root, { recursive: true, force: true }) }
})

test('a subagent is anchored at the parent line that spawned it, not the parent end', async () => {
  // Every subagent of a real session landed on one card because index.js passed
  // seedLength 0: the canvas keeps parent cards with `sourceSeq < seedLength`,
  // so 0 selects nothing and every agent fell back to the same anchor.
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-spawnline-'))
  const main = 'aaaaaaaa-1111-2222-3333-444444444444'
  const project = join(root, 'F--Project-Demo')
  const subagents = join(project, main, 'subagents')
  await mkdir(subagents, { recursive: true })
  const write = (path, lines) => writeFile(path, Array.isArray(lines) ? lines.map(line => `${JSON.stringify(line)}\n`).join('') : lines, 'utf8')

  await write(join(project, `${main}.jsonl`), [
    userLine('第一问'),                                                  // line 0
    assistantLine('m1', 0, { type: 'text', text: '第一答' }),            // line 1
    userLine('第二问'),                                                  // line 2
    assistantLine('m2', 0, { type: 'tool_use', id: 'call_spawn', name: 'Agent', input: { prompt: 'go' } }),   // line 3
    userLine('第三问'),                                                  // line 4
  ])
  await write(join(subagents, 'agent-zzz.jsonl'), [userLine('子代理的提问')])
  await write(join(subagents, 'agent-zzz.meta.json'), JSON.stringify({ toolUseId: 'call_spawn', spawnDepth: 1 }))

  try {
    const source = new TranscriptSource(root)
    await source.sync(stubStore(), 'T')
    const child = source.sessions.get('agent-zzz')
    assert.equal(child.parentSessionId, main)
    assert.equal(child.parentSeedLength, 4, 'the spawning line (3) is inside the cut, so the agent anchors there')
  } finally { await rm(root, { recursive: true, force: true }) }
})

test('a fork copy does not adopt the subagents of the session it copied', async () => {
  // A fork duplicates its parent's assistant lines, so the tool_use that spawned
  // a subagent exists in both files under the same id and the issuer index hands
  // back whichever file was read first. Resolving to the copy is wrong twice
  // over: the agent hangs off a session it was never spawned in, and its anchor
  // is counted in that file's line space. The copy sorts first on purpose, which
  // is the order that made a real corpus resolve three agents to a fork.
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-forkcopy-'))
  const main = 'aaaaaaaa-1111-2222-3333-444444444444'
  const copy = '00000000-9999-8888-7777-666666666666'
  const project = join(root, 'F--Project-Demo')
  const subagents = join(project, main, 'subagents')
  await mkdir(subagents, { recursive: true })
  const write = (path, lines) => writeFile(path, Array.isArray(lines) ? lines.map(line => `${JSON.stringify(line)}\n`).join('') : lines, 'utf8')

  const history = [
    userLine('第一问'),                                                  // line 0
    assistantLine('m1', 0, { type: 'text', text: '第一答' }),            // line 1
    userLine('第二问'),                                                  // line 2
    assistantLine('m2', 0, { type: 'tool_use', id: 'call_spawn', name: 'Agent', input: { prompt: 'go' } }),   // line 3
    userLine('第三问'),                                                  // line 4
  ]
  await write(join(project, `${main}.jsonl`), history)
  // One line longer, so a wrong pick is visible in the anchor too (line 4 vs 3).
  await write(join(project, `${copy}.jsonl`), [{ type: 'summary', summary: '副本', sessionId: copy }, ...history])
  await write(join(subagents, 'agent-zzz.jsonl'), [userLine('子代理的提问')])
  await write(join(subagents, 'agent-zzz.meta.json'), JSON.stringify({ toolUseId: 'call_spawn', spawnDepth: 1 }))

  try {
    const source = new TranscriptSource(root)
    await source.sync(stubStore(), 'T')
    assert.equal(source.sessions.get(copy).issuedToolCalls.has('call_spawn'), true,
      'the fixture is only meaningful if the copy really does issue the same call')
    const child = source.sessions.get('agent-zzz')
    assert.equal(child.parentSessionId, main, 'the folder the agent was written under spawned it')
    assert.equal(child.parentSeedLength, 4, 'and the anchor is the spawning line in THAT file, not in the copy')
  } finally { await rm(root, { recursive: true, force: true }) }
})

test('a subagent whose spawner is not in this run keeps the directory parent', async () => {
  // toolUseId names a call nobody in the corpus issued (project deleted, spawner
  // gone): falling back to the directory beats leaving the agent orphaned.
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-orphan-'))
  const main = 'bbbbbbbb-1111-2222-3333-444444444444'
  const subagents = join(root, 'F--Project-Demo', main, 'subagents')
  await mkdir(subagents, { recursive: true })
  const write = (path, lines) => writeFile(path, Array.isArray(lines) ? lines.map(line => `${JSON.stringify(line)}\n`).join('') : lines, 'utf8')
  await write(join(root, 'F--Project-Demo', `${main}.jsonl`), [userLine('提问')])
  await write(join(subagents, 'agent-ccc.jsonl'), [userLine('提问')])
  await write(join(subagents, 'agent-ccc.meta.json'), JSON.stringify({ toolUseId: 'call_gone', spawnDepth: 2 }))
  try {
    const source = new TranscriptSource(root)
    await source.sync(stubStore(), 'T')
    assert.equal(source.sessions.get('agent-ccc').parentSessionId, main)
    // No resolved spawner means no known spawn line: leaving this undefined is
    // what makes index.js fall back to seedLength 0, i.e. the old anchor.
    assert.equal(source.sessions.get('agent-ccc').parentSeedLength, undefined)
  } finally { await rm(root, { recursive: true, force: true }) }
})

test('detectForks links a child whose leading prompts are a prefix of the parent', () => {
  const sessions = new Map([
    ['parent', { id: 'parent', fingerprint: ['a', 'b'], turnSeqs: [5, 20], lastSeq: 40 }],
    ['child', { id: 'child', fingerprint: ['a', 'b', 'c'], turnSeqs: [5, 20, 31], lastSeq: 50 }],
    ['unrelated', { id: 'unrelated', fingerprint: ['z'], turnSeqs: [3], lastSeq: 9 }],
  ])
  const forks = detectForks(sessions)
  assert.deepEqual([...forks.keys()], ['child'])
  // seedLength is in the PARENT's seq space: the boundary sits at the parent's
  // next turn, so exactly the two shared turns stay inside the fork cut.
  assert.deepEqual(forks.get('child'), { parentSessionId: 'parent', seedLength: 40 })
})

test('a fork is linked but a re-asked question is not, end to end', async () => {
  // A `--fork-session` copy preserves replies verbatim; re-sending the same
  // prompt in a fresh session produces a different answer. Both look identical
  // if you fingerprint only the questions, which is what made two ordinary
  // retries show up as branches on a real corpus.
  const root = await mkdtemp(join(tmpdir(), 'ccsynapse-fork-'))
  const project = join(root, 'F--Project-Demo')
  await mkdir(project, { recursive: true })
  const write = async (id, lines, extra = []) => writeFile(join(project, `${id}.jsonl`), [...lines, ...extra].map(line => `${JSON.stringify(line)}\n`).join(''), 'utf8')

  const turn = (prompt, answer) => [
    userLine(prompt),
    assistantLine(prompt, 0, { type: 'text', text: answer }),
    // A new prompt closes the previous turn, so give each turn a successor.
  ]
  const close = () => [userLine('下一问'), assistantLine('下一问', 0, { type: 'text', text: '下一答' })]

  const t1 = turn('q1', 'a1')
  const t2 = turn('q2', 'a2')
  await write('parent000-0000-0000-0000-000000000000', [...t1, ...t2, ...close()])
  // Fork: identical history, one extra turn appended.
  await write('child0000-0000-0000-0000-000000000000', [...t1, ...t2, ...close(), userLine('分支的新问题')])
  // Retry: same questions, different answers.
  await write('retry0000-0000-0000-0000-000000000000', [
    userLine('q1'), assistantLine('q1', 0, { type: 'text', text: 'DIFFERENT' }),
    userLine('q2'), assistantLine('q2', 0, { type: 'text', text: 'ALSO DIFFERENT' }),
    ...close(),
  ])

  try {
    const source = new TranscriptSource(root)
    await source.sync(stubStore(), 'T')
    const forks = detectForks(source.sessions)
    assert.deepEqual([...forks.keys()], ['child0000-0000-0000-0000-000000000000'],
      'only the verbatim copy is a fork; the retry is not')
    assert.equal(forks.get('child0000-0000-0000-0000-000000000000').parentSessionId, 'parent000-0000-0000-0000-000000000000')
  } finally { await rm(root, { recursive: true, force: true }) }
})

test('detectForks prefers the longest matching parent and ignores non-prefixes', () => {
  const sessions = new Map([
    ['root', { id: 'root', fingerprint: ['a', 'b'], turnSeqs: [1, 8], lastSeq: 25 }],
    ['mid', { id: 'mid', fingerprint: ['a', 'b', 'c'], turnSeqs: [1, 8, 19], lastSeq: 40 }],
    ['leaf', { id: 'leaf', fingerprint: ['a', 'b', 'c', 'd'], turnSeqs: [1, 8, 19, 30], lastSeq: 50 }],
    ['other', { id: 'other', fingerprint: ['a', 'x', 'y'], turnSeqs: [1, 4, 9], lastSeq: 12 }],
  ])
  const forks = detectForks(sessions)
  assert.equal(forks.get('leaf').parentSessionId, 'mid', 'longest shared prefix wins, not root')
  assert.equal(forks.get('mid').parentSessionId, 'root')
  assert.equal(forks.has('other'), false, 'a diverging second prompt is not a fork')
})

test('detectForks needs more than one shared turn, so a common opener is not a fork', () => {
  // "你好" opens many unrelated sessions; one shared turn must not link them.
  const sessions = new Map([
    ['first', { id: 'first', fingerprint: ['hi', 'a'], turnSeqs: [1, 8], lastSeq: 20 }],
    ['second', { id: 'second', fingerprint: ['hi', 'b'], turnSeqs: [1, 8], lastSeq: 20 }],
  ])
  assert.equal(detectForks(sessions).size, 0)
  assert.equal(detectForks(sessions, 1).size, 0, 'neither is a strict prefix of the other')
})

test('detectForks uses UUID intersection when available, never misidentifies a retry', async () => {
  // Fork: the child is a stale snapshot, so it holds a SUBSET of the parent's
  // UUIDs — the original is the one that kept appending.
  const parentUuids = new Set(['u1', 'u2', 'u3', 'u4', 'u5'])
  const childUuids  = new Set(['u1', 'u2', 'u3'])               // subset
  const retryUuids  = new Set(['r1', 'r2', 'r3'])               // disjoint

  const sessions = new Map([
    ['parent', { id: 'parent', uuidSet: parentUuids, fingerprint: [], turnSeqs: [], lastSeq: 50 }],
    ['child',  { id: 'child',  uuidSet: childUuids,  fingerprint: [], turnSeqs: [], lastSeq: 30 }],
    ['retry',  { id: 'retry',  uuidSet: retryUuids,  fingerprint: [], turnSeqs: [], lastSeq: 30 }],
  ])
  const forks = detectForks(sessions)
  assert.deepEqual([...forks.keys()], ['child'], 'only the UUID-subset is a fork')
  assert.equal(forks.get('child').parentSessionId, 'parent')
  assert.equal(forks.has('retry'), false, 'disjoint UUIDs are never a fork')
  assert.equal(forks.has('parent'), false, 'the original is never a child')
})

test('detectForks assigns the larger session as parent, so snapshots are siblings', () => {
  // A fork is a snapshot of the original: the original keeps growing, so it
  // holds MORE uuids. Three snapshots taken at different times all descend
  // from that one original — they must be siblings, not a chain.
  const core = ['u1', 'u2', 'u3', 'u4', 'u5']
  const sessions = new Map([
    ['origin', { id: 'origin', uuidSet: new Set([...core, 'o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'o8']), fingerprint: [], turnSeqs: [], lastSeq: 100 }],
    ['snapA',  { id: 'snapA',  uuidSet: new Set(core), fingerprint: [], turnSeqs: [], lastSeq: 30 }],
    ['snapB',  { id: 'snapB',  uuidSet: new Set([...core, 'o1', 'o2']), fingerprint: [], turnSeqs: [], lastSeq: 50 }],
  ])
  const forks = detectForks(sessions)
  assert.equal(forks.get('snapA')?.parentSessionId, 'origin')
  assert.equal(forks.get('snapB')?.parentSessionId, 'origin')
  assert.equal(forks.has('origin'), false, 'the original is never a child')
})

test('detectForks anchors each snapshot at its own fork line, not the parent end', () => {
  // Parent keeps growing; two snapshots were taken at different points.
  // Each must get the seedLength of ITS fork cut so the canvas anchors the
  // branch where it really forked.
  const sessions = new Map([
    ['origin', {
      id: 'origin', fingerprint: [], turnSeqs: [], lastSeq: 900,
      uuidSet: new Set(['a', 'b', 'c', 'd', 'e', 'f']),
      uuidLine: new Map([['a', 10], ['b', 20], ['c', 30], ['d', 40], ['e', 50], ['f', 60]]),
    }],
    ['early', {
      id: 'early', fingerprint: [], turnSeqs: [], lastSeq: 40,
      uuidSet: new Set(['a', 'b', 'c']),           // forked after parent line 30
      uuidLine: new Map([['a', 5], ['b', 15], ['c', 25]]),
    }],
    ['late', {
      id: 'late', fingerprint: [], turnSeqs: [], lastSeq: 60,
      uuidSet: new Set(['a', 'b', 'c', 'd', 'e']), // forked after parent line 50
      uuidLine: new Map([['a', 5], ['b', 15], ['c', 25], ['d', 35], ['e', 45]]),
    }],
  ])
  const forks = detectForks(sessions)
  assert.equal(forks.get('early').parentSessionId, 'origin')
  assert.equal(forks.get('early').seedLength, 31, 'anchored just past parent line 30')
  assert.equal(forks.get('late').parentSessionId, 'origin')
  assert.equal(forks.get('late').seedLength, 51, 'anchored just past parent line 50')
})

// --- in-session branches ----------------------------------------------------
// The other lineage shape, and the rarer one: two questions in ONE session that
// answer the same earlier line. A whole corpus of 47 session files holds two of
// them. Nothing else on disk says so — the retry is an ordinary `user` line with
// a string body, and the prompt it replaces is simply left unanswered.

const systemLine = (uuid) => ({ type: 'system', subtype: 'init', uuid, timestamp: '2026-01-01T00:00:00.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1' })
const promptLine = (uuid, parentUuid, text) => ({ type: 'user', uuid, parentUuid, timestamp: '2026-01-01T00:00:00.000Z', cwd: 'F:\\Project\\Demo', sessionId: 's1', message: { role: 'user', content: text } })

test('a question answered from an earlier turn than its predecessor is a branch', async () => {
  const { root, cleanup } = await fixture([
    systemLine('s0'),                                            // line 0 — answered by 问题一
    promptLine('u1', 's0', '问题一'),                             // line 1
    assistantLine('m1', 0, { type: 'text', text: '答复一' }),     // line 2
    systemLine('s1'),                                            // line 3 — the point the user went back to
    promptLine('u2', 's1', '问题二'),                             // line 4
    assistantLine('m2', 1, { type: 'text', text: '答复二' }),     // line 5
    promptLine('u3', 's1', '问题二（改）'),                        // line 6 — re-asked from line 3
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    const prompts = store.projected.filter(event => event.type === 'user/message')
    assert.deepEqual(prompts.map(event => event.seq), [1, 4, 6])
    assert.equal(prompts[1].data.parentSeq, 3, '问题二 answers the line above it')
    // 问题二（改）answers line 3, NOT the reply on line 5 that it follows. That
    // difference is the entire branch: the canvas hangs both questions, and only
    // both questions, off the card that owns line 3.
    assert.equal(prompts[2].data.parentSeq, 3, 'the retry answers an earlier line, not its predecessor')

    // End to end: the field has to survive the store or the canvas sees nothing.
    const { WorkspaceStore } = await import('../server/workspace-store.js')
    const directory = await mkdtemp(join(tmpdir(), 'ccsynapse-store-'))
    const workspaceStore = new WorkspaceStore(join(directory, 'state.json'))
    const session = { id: 'sess', title: 'T', header: { cwd: 'F:\\Project\\Demo' }, firstLiveSeq: 0, events: store.projected }
    const thread = await workspaceStore.projectSession(session, 0, 'T')
    assert.deepEqual(thread.messages.filter(message => message.kind === 'user').map(message => message.sourceParentSeq), [0, 3, 3])
    await rm(directory, { recursive: true, force: true })
  } finally { await cleanup() }
})

test('a linear conversation points every prompt at the line above it', async () => {
  // The control. In a session where nobody ever went back, each prompt answers
  // the line immediately above it, so nothing here may read as a fork.
  const { root, cleanup } = await fixture([
    systemLine('s0'),                                            // line 0
    promptLine('u1', 's0', '问题一'),                             // line 1
    assistantLine('m1', 0, { type: 'text', text: '答复一' }),     // line 2
    promptLine('u2', 'a0', '问题二'),                             // line 3
    assistantLine('m2', 1, { type: 'text', text: '答复二' }),     // line 4
    promptLine('u3', 'a1', '问题三'),                             // line 5
  ])
  try {
    const store = stubStore()
    await new TranscriptSource(root).sync(store, 'T')
    const prompts = store.projected.filter(event => event.type === 'user/message')
    assert.deepEqual(prompts.map(event => event.data.parentSeq), [0, 2, 4])
    assert.deepEqual(
      prompts.map(event => event.data.parentSeq),
      prompts.map(event => event.seq - 1),
      'a linear session chains, so no card may resolve to a sibling',
    )
  } finally { await cleanup() }
})

test('the canvas resolves an answered line to the turn that owns it', async () => {
  // The last hop: a card holds `sourceParentSeq`, and the canvas turns it into
  // a parent card. A turn spans from its own question to just before the next
  // one, so the answer is the last turn starting at or below that line. A line
  // above every turn resolves to nothing, which is what sends the caller back
  // to the linear chain instead of leaving a card with no edge at all.
  const source = await readFile(new URL('../web/app.js', import.meta.url), 'utf8')
  const slice = source.slice(source.indexOf('function turnCardContaining'), source.indexOf('function conversationCards'))
  const context = { globalThis: {} }
  vm.createContext(context)
  vm.runInContext(`${slice};globalThis.turnCardContaining = turnCardContaining`, context)
  const { turnCardContaining } = context.globalThis
  // The 4efe8a21 shape: a question at line 670 whose answered line 669 belongs
  // to the turn opened at 519, so it must NOT become the child of the card at 670.
  const siblings = [{ id: 'turn:519', sourceSeq: 519 }, { id: 'turn:670', sourceSeq: 670 }, { id: 'turn:756', sourceSeq: 756 }]
  assert.equal(turnCardContaining(siblings, 669).id, 'turn:519')
  assert.equal(turnCardContaining(siblings, 670).id, 'turn:670', 'a question owns itself')
  assert.equal(turnCardContaining(siblings, 755).id, 'turn:670')
  assert.equal(turnCardContaining(siblings, 4), undefined, 'above every turn -> the linear fallback')
  assert.equal(turnCardContaining([{ id: 'empty', sourceSeq: undefined }], 9), undefined, 'a placeholder card owns no line')
})

test('a shrunk-in-place transcript re-indexes the parent line instead of reusing the old one', async () => {
  // Rewriting a transcript shorter moves EVERY later line, so an index built
  // before the rewrite now names the wrong line — the prompt at old line 14 is
  // at 11 after three tool results are removed, and its parent (old line 13) is
  // at 10. Holding the stale `uuidLine` entry resolves the parent to 13, a seq
  // past its own: the card becomes its own ancestor, drawing an edge and a fold
  // button that both point at itself.
  const toolUse = { type: 'tool_use', id: 'tu1', name: 'bash', input: {} }
  const generations = [
    [
      systemLine('s0'),                                     // 0
      promptLine('u1', 's0', '问题一'),                      // 1  -> answered line 0
      assistantLine('m1', 0, { type: 'text', text: '答复一' }),  // 2
      assistantLine('m1b', 1, toolUse),                     // 3
      toolResultLine('tu1', '结果一'),                        // 4
      toolResultLine('tu1', '结果二'),                        // 5  \
      toolResultLine('tu1', '结果三'),                        // 6   > removed in gen 2
      assistantLine('m2', 2, { type: 'text', text: '答复二' }),  // 7
      promptLine('u2', 'a2', '问题二'),                      // 8  -> answered line 7
      assistantLine('m3', 3, { type: 'text', text: '答复三' }),  // 9
      toolResultLine('tu1', '结果四'),                        // 10 /
      systemLine('s9'),                                     // 11
      assistantLine('m4', 4, { type: 'text', text: '答复四' }),  // 12
      systemLine('s10'),                                    // 13 <- answered line
      promptLine('u3', 's10', '问题三'),                     // 14
    ],
    [
      systemLine('s0'),                                     // 0
      promptLine('u1', 's0', '问题一'),                      // 1
      assistantLine('m1', 0, { type: 'text', text: '答复一' }),  // 2
      assistantLine('m1b', 1, toolUse),                     // 3
      toolResultLine('tu1', '结果一'),                        // 4
      assistantLine('m2', 2, { type: 'text', text: '答复二' }),  // 5
      promptLine('u2', 'a2', '问题二'),                      // 6
      assistantLine('m3', 3, { type: 'text', text: '答复三' }),  // 7
      systemLine('s9'),                                     // 8
      assistantLine('m4', 4, { type: 'text', text: '答复四' }),  // 9
      systemLine('s10'),                                    // 10 <- answered line
      promptLine('u3', 's10', '问题三'),                     // 11
    ],
  ]
  const write = (lines) => lines.map(line => `${JSON.stringify(line)}\n`).join('')
  const { root, file, cleanup } = await fixture(generations[0])
  try {
    const store = stubStore()
    const source = new TranscriptSource(root)
    await source.sync(store, 'T')
    assert.deepEqual(store.projected.filter(event => event.type === 'user/message').map(event => event.data.parentSeq), [0, 7, 13])

    await writeFile(file, write(generations[1]), 'utf8')
    await source.sync(store, 'T')
    const prompts = store.projected.filter(event => event.type === 'user/message')
    const rewritten = prompts.at(-1)
    assert.equal(rewritten.seq, 11, 'the shrinking rewrite moved the prompt')
    assert.equal(rewritten.data.parentSeq, 10, 'the parent line is re-indexed, not the stale 13')
    assert.ok(prompts.every(event => !Number.isInteger(event.data.parentSeq) || event.data.parentSeq < event.seq),
      'no prompt may answer a line at or after itself')

    // End to end: the value the store records is what the canvas reads.
    const { WorkspaceStore } = await import('../server/workspace-store.js')
    const directory = await mkdtemp(join(tmpdir(), 'ccsynapse-store-'))
    const workspaceStore = new WorkspaceStore(join(directory, 'state.json'))
    await workspaceStore.projectSession({ id: 'sess', title: 'T', header: { cwd: 'F:\\Project\\Demo' }, firstLiveSeq: 0, events: store.projected }, 0, 'T')
    const stored = await workspaceStore.get((await workspaceStore.list())[0].id)
    const messages = stored.threads[0].messages.filter(message => message.kind === 'user')
    assert.ok(messages.every(message => !Number.isInteger(message.sourceParentSeq) || message.sourceParentSeq < message.sourceSeq),
      `a card must never parent itself: ${JSON.stringify(messages.map(m => [m.sourceSeq, m.sourceParentSeq]))}`)
    await rm(directory, { recursive: true, force: true })
  } finally { await cleanup() }
})
